language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7
        - CXXSTD="-std=c++17"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=clang++

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env:
        - COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env:
        - COMPILER=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - COMPILER=clang++-3.7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env:
        - COMPILER=clang++-3.8

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9']
      env:
        - COMPILER=clang++-3.9

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILER=clang++-4.0

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILER=clang++-4.0
        - CXXSTD="-std=c++1z"

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - COMPILER=clang++

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - COMPILER=clang++

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - COMPILER=clang++

    - language: android
      jdk: openjdk7
      android:
        components:
          - tools
          - build-tools-23.0.3
          - extra-android-support
          - extra-android-m2repository
          - android-22
          - sys-img-armeabi-v7a-android-22
          - cmake
        licenses:
          - '.+'
      before_script:
        - export TERM=dumb
        - curl -L http://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -O
        - unzip -q android-ndk-r10e-linux-x86_64.zip
        - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
        - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
        - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
        - export PATH=$PATH:${ANDROID_NDK_HOME}
        - export CMAKE_VERSION=3.6.2
        - curl -L https://cmake.org/files/v3.6/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz -O
        - tar xzf cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
        - export PATH=cmake-${CMAKE_VERSION}-Linux-x86_64/bin:$PATH
        - export _NO_CHECK_SIGNATURE=true
        - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator || android-wait-for-emulator
      script:
        - cmake -DANDROID_NDK="$ANDROID_NDK_HOME" -DANDROID_ABI=armeabi-v7a -DPEGTL_BUILD_EXAMPLES=OFF
        - make -j2
        - make test

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7
        - CXXFLAGS="-O0 --coverage"
      before_script:
        - pip install --user urllib3[secure] cpp-coveralls
        # Work around https://github.com/eddyxu/cpp-coveralls/issues/108 by manually
        # installing the pyOpenSSL module and injecting it into urllib3 as per
        # https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
        - sed -i -e '/^import sys$/a import urllib3.contrib.pyopenssl\nurllib3.contrib.pyopenssl.inject_into_urllib3()' $(which coveralls)
      script:
        - make CXX=$COMPILER -j3 check
        - coveralls --gcov gcov-7 --gcov-options '\-lp' --exclude src

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7
        - CPPFLAGS=-fsanitize=undefined

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6
        - CPPFLAGS="-fsanitize=address -fuse-ld=gold"

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILER=clang++-4.0
        - CPPFLAGS=-fsanitize=undefined

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILER=clang++-4.0
        - CPPFLAGS=-fsanitize=address

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'valgrind']
      env:
        - COMPILER=g++-6
        - SPECIAL=valgrind
      script:
        - make CXX=$COMPILER -j3 valgrind

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'cppcheck']
      env:
        - COMPILER=g++-6
        - SPECIAL=cppcheck
      script:
        - make CXX=$COMPILER -j3 cppcheck

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0', 'clang-tidy-4.0']
      env:
        - COMPILER=clang++-4.0
        - CLANG_TIDY=clang-tidy-4.0
      script:
        - make CXX=$COMPILER -j3 clang-tidy

script:
  make CXX=$COMPILER -j3
