language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.7']
      env:
        - COMPILER=g++-4.7

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6

    - os: linux
      compiler: clang
      env:
        - COMPILER=clang++

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env:
        - COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env:
        - COMPILER=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - COMPILER=clang++-3.7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env:
        - COMPILER=clang++-3.8

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9']
      env:
        - COMPILER=clang++-3.9

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILER=clang++-4.0

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - COMPILER=clang++

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - COMPILER=clang++

    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env:
        - COMPILER=clang++

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6
        - CXXFLAGS="-O0 --coverage"
      before_script:
        - pip install --user cpp-coveralls
      script:
        - make CXX=$COMPILER -j3 check
      after_success:
        - coveralls --gcov gcov-6 --gcov-options '\-lp' --exclude unit_tests --exclude examples

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - CPPFLAGS=-fsanitize=undefined
        - COMPILER=g++-6

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - CPPFLAGS="-fsanitize=address -fuse-ld=gold"
        - COMPILER=g++-6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env:
        - CPPFLAGS=-fsanitize=undefined
        - COMPILER=clang++-3.8

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env:
        - CPPFLAGS=-fsanitize=address
        - COMPILER=clang++-3.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'valgrind']
      env:
        - COMPILER=g++-6
        - SPECIAL=valgrind
      script:
        - make CXX=$COMPILER -j3 valgrind

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'cppcheck']
      env:
        - COMPILER=g++-6
        - SPECIAL=cppcheck
      script:
        - make CXX=$COMPILER -j3 cppcheck

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8', 'clang-tidy-3.8']
      env:
        - COMPILER=clang++-3.8
        - CLANG_TIDY=clang-tidy-3.8
      script:
        - make CXX=$COMPILER -j3 clang-tidy

script:
  make CXX=$COMPILER -j3
