name: Linux

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-7
          - g++-8
          - g++-9
          - g++-10
          - clang++-8
          - clang++-9
          - clang++-10
          - clang++-11
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  linux-gcc-extra:
    strategy:
      fail-fast: false
      matrix:
        flags: ["-fno-rtti"]
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="${{ matrix.flags }}"

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  linux-clang-extra:
    strategy:
      fail-fast: false
      matrix:
        flags: ["-fno-rtti", "-fms-extensions"]
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      CXX: clang++

    steps:
    - uses: actions/checkout@v2

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="${{ matrix.flags }}"

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  clang-conanio:
    strategy:
      fail-fast: false
      matrix:
        image:
          # List: https://github.com/conan-io/conan-docker-tools
          - clang50
          - clang60
          - clang7
          - clang9-x86
        build_type: [Debug, Release]

    container:
      image: conanio/${{ matrix.image }}
      options: --user root

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure
